### ISSUE TITLE
Could --allow_self_payment remove the requirement for two instances of lnd?

### ISSUE THREAD

**Issue by HamishMacEwan** [asoltys/coinos-server#10]
Hi,

Awesome, awesome service.  Rivals lnbits.com.

The subject pretty much says it all.  

This on-going issue for hosted accounts (LndHub from the host to an account, and vice versa) is a weird problem.

I appreciate self_payment requires at least a channel to another instance, but I don't have to manage that in the same box...

**Comment by asoltys** [comment]
Hi, thanks for the kind words! I had considered using that flag a while ago instead of having two instances but didn't like the idea of having routing fees when sending payments between users. I just recently [removed the second lnd instance altogether](https://github.com/asoltys/coinos-server/commit/cc6249b0afe23f7a9d43c58ad6da79595c8c1645) so now when you attempt to pay a lightning invoice from another coinos user, you'll just be prompted to send an internal transfer. Same goes for sending on-chain BTC or Liquid to another user. You used to have the option of doing it on-chain or internally but now the UI only lets you do it internally.
